### ISSUE TITLE
Total de jours attendu

### ISSUE THREAD

**Issue by Yimiprod** [LinkValue/CraCra#24]
Est-ce normal que le nombre de jours attendu pour un mois soit indique 30 jours quand il y 20 jours ouvert dans le mois :
![capture d ecran 2016-11-22 a 17 03 09](https://cloud.githubusercontent.com/assets/2227867/20531032/af7b035e-b0d5-11e6-8c6b-8f8819582d1f.png)

**Comment by Yimiprod** [comment]
C'est moi ou tu l'a fixé @D34THWINGS ?

**Comment by D34THWINGS** [comment]
@Yimiprod j'ai pas poussé de code en prod depuis hier dessus donc normalement non

**Comment by Yimiprod** [comment]
Du coup j'ai compris, en fait quand on reload la page et qu'on lance un print, le `nombre de jours attendus :` redeviens correct.
