### ISSUE TITLE
error sur clic sur icone impression

### ISSUE THREAD

**Issue by lvrbacconnier** [LinkValue/CraCra#34]
<img width="1420" alt="capture d ecran 2016-11-29 a 16 22 18" src="https://cloud.githubusercontent.com/assets/17824540/20715656/2cd15842-b650-11e6-8854-116322a28330.png">

**Comment by D34THWINGS** [comment]
Les erreurs dans la console n'ont rien à voir, c'est le cache de l'offline mode qui n'est pas content. Mais je vais instiguer le bug pour voir quel est le problème
